version: 2

sources:
  - name: src
    database: sourcedb
    description: source data from oracle
    schema: mk_mall
    tables:
      - name: customers
        columns:
          - name: c_custkey
            tests:
              - unique
              - not_null
                 
              
      - name: nations
        description: Nation id details
      - name: regions
      - name: suppliers
        freshness: 
          error_after:
            count: 2
            period: minute
          warn_after:
            count: 1
            period: minute
        loaded_at_field: updated_time
